#!/bin/bash
sudo useradd newuser

sudo runuser -l newuser -c 'mkdir .ssh' 

sudo runuser -l newuser -c 'chmod -R 700 .ssh'

sudo runuser -l newuser -c 'cd .ssh'

sudo runuser -l newuser -c 'echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDumykJJXIg/AyXDyTwcAXYSzjb+1BnNBMmfn4I2iRfGNsbxFgYb0+XtYIo+hkK78EPYnRkIzUojRZlV7ypYX04FRn9xkU+O75H6eEnl1ylfN8qqDGAk372vuXgOTO1K6uAtX330UA09E9OUhky4NLGZGRhw9BU+nJZ5Xp3qQ7yL0crtBqtlaC3CR8M5rGbVqmcDWZRtLf9B0yS2cQYjrCyZ8pDfOwNFfCfVNypl+4EbcNuw/AzBYEi/PcrqhUuKUvwMdfp1+x3Txrw4UtDYfJrmV38FMuK0QURdlQGlpfCf2JWgvM4d8BV9H1PF3XTjrE3ysnkzfzOqSjMN83jpNb sabeehah1996@golang" > ~/.ssh/authorized_keys'

sudo runuser -l newuser -c 'chmod 600 ~/.ssh/authorized_keys'
